- name: Pull and Run docker image
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull rohitg24/scientific_calculator
      docker_image:
        name: rohitg24/scientific_calculator
        source: pull